apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: variable-vole-python 
  janus-idp.io/tekton: variable-vole-python
  backstage.io/kubernetes-id: variable-vole-python
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: variable-vole-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  